### ISSUE TITLE
Some weight paths downloaded from Huggingface do not match those in app.py

### ISSUE THREAD

**Issue by whu125** [AlonzoLeeeooo/StableV2V#12]
Thanks for your excellent work!

I have successfully reproduced it and achieved good results.

However, I noticed a few path errors during the reproduction process, which occurred in **app.py**.

For example:  
`args.controlnet_checkpoint_path = "checkpoints/controlnet-v1.1-diffusers/depth"`

In reality, the path downloaded from Huggingface is **controlnet-depth**.

Additionally, there is another path, **controlnet-scribble**. I'm not sure what the difference is between the two, so I'm unsure if modifying it to **controlnet-depth** is correct.

**Comment by AlonzoLeeeooo** [comment]
HI @whu125 ,

Thank you so much for pointing this out! And yes, your modification is correct.

`controlnet-v1.1-diffusers/depth` is the path on my testing ends, and also `ctrl-adapter/i2vgenxl-depth`. These typos are now fixed in [the latest commit](https://github.com/AlonzoLeeeooo/StableV2V/commit/3a66b37a7a0264efbac062309bac4d2f927bc55b). The paths in `app.py` should correspond to the ones in our [HuggingFace repository](https://huggingface.co/AlonzoLeeeooo/StableV2V) currently.

Feel free to let us know if any other error proceeds! Thanks for your valuable information!

Best regards,
Chang

**Comment by AlonzoLeeeooo** [comment]
`controlnet-scribble` is used for the sketch-based editing scenario, where the ControlNet in this model weights takes user sketch as the condition input. For instruction of performing the sketch-based editing application, please follow our instructions in [this section](https://github.com/AlonzoLeeeooo/StableV2V#performing-sketch-based-editing-with-stablev2v).
