### ISSUE TITLE
Why is the effect of my reproduction so poor?

### ISSUE THREAD

**Issue by Weiwenliang123** [AlonzoLeeeooo/StableV2V#16]
I used the following instructions：
CUDA_VISIBLE_DEVICES=1 python inference.py --raft-checkpoint-path checkpoints/raft-things.pth --midas-checkpoint-path checkpoints/[dpt_swin2_large_384.pt](http://dpt_swin2_large_384.pt/) --u2net-checkpoint-path checkpoints/u2net.pth  --stable-diffusion-checkpoint-path checkpoints/stable-diffusion-v1.5 --controlnet-checkpoint-path checkpoints/controlnet-depth --i2vgenxl-checkpoint-path checkpoints/i2vgenxl --ctrl-adapter-checkpoint-path checkpoints/ctrl-adapter-i2vgenxl-depth --completion-net-checkpoint-path checkpoints/50000.ckpt --image-editor-type instructpix2pix --image-editor-checkpoint-path checkpoints/instruct-pix2pix --source-video-frames inputs/frames/bear --external-guidance inputs/reference-images/raccoon.jpg --prompt "a raccoon" --outdir results

source image
![00000](https://github.com/user-attachments/assets/969e78ff-2772-45b9-a9e1-679d900c828a)

reference image
![raccoon](https://github.com/user-attachments/assets/71f94f75-2d70-493b-a071-5da674747148)

results
![a_raccoon](https://github.com/user-attachments/assets/e11605a7-b17c-4f46-bf5f-7d0953ef22b3)

**Comment by AlonzoLeeeooo** [comment]
Hi @Weiwenliang123 ,

Thanks for your interest! It seems that the poor reproduction is caused by the quality of first edited frame. And you can easily fix this by offering the proper hyper-parameters.

In your case, it seems that you are using a large mask region for Paint-by-Example and it edits the first frame to a much larger region, so that the later processes propagates this wrongly edited frame to the entire video.

To solve this, we recommend you to use a smaller value of `--kernel-size` and `--dilation-iteration`, so that the binary dilation process won't make the mask region too large for Paint-by-Example. Personally I recommend something like `--kernel-size 11` and `--dilation-iteration 3` (which should keep the mask size almost the same).

Also, note that you can start with specific edited first frame, so that the code will skip the first-frame editing process. And we recommend you to do this since it performs much better. Particularly, I've execute Paint-by-Example on my ends with your inputs, where you can start with the following first edited frame:
<img width="505" alt="image" src="https://github.com/user-attachments/assets/aaf8257a-64d0-4b94-a2d9-c47b59927516">

If you meet any further problems, please do not hesitate to contact us again! Thanks!

**Comment by Weiwenliang123** [comment]
Thanks for your reply. However, I used InstructPix2Pix instead of Paint-by-Example.


CUDA_VISIBLE_DEVICES=1 python inference.py --raft-checkpoint-path checkpoints/raft-things.pth --midas-checkpoint-path checkpoints/dpt_swin2_large_384.pt&nbsp;--u2net-checkpoint-path checkpoints/u2net.pth --stable-diffusion-checkpoint-path checkpoints/stable-diffusion-v1.5 --controlnet-checkpoint-path checkpoints/controlnet-depth --i2vgenxl-checkpoint-path checkpoints/i2vgenxl --ctrl-adapter-checkpoint-path checkpoints/ctrl-adapter-i2vgenxl-depth --completion-net-checkpoint-path checkpoints/50000.ckpt --image-editor-type instructpix2pix --image-editor-checkpoint-path checkpoints/instruct-pix2pix --source-video-frames inputs/frames/bear --external-guidance inputs/reference-images/raccoon.jpg --prompt "a raccoon" --outdir results












魏文亮
***@***.***

15176760368

---Original---
From: ***@***.***&gt;
Date: Sat, Dec 7, 2024 12:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [AlonzoLeeeooo/StableV2V] Why is the effect of my reproduction sopoor? (Issue #16)




 
Hi @Weiwenliang123 ,
 
Thanks for your interest! It seems that the poor reproduction is caused by the quality of first edited frame. And you can easily fix this by offerin proper hyper-parameters.
 
In your case, it seems that you are using a large mask region for Paint-by-Example and it edits the first frame to a much larger region, so that the later processes propagates this wrongly edited frame to the entire video.
 
To solve this, we recommend you to use a smaller value of --kernel-size and --dilation-iteration, so that the binary dilation process won't make the mask region too large for Paint-by-Example. Personally I recommend something like --kernel-size 11 and --dilation-iteration 3 (which should keep the mask size almost the same).
 
Also, note that you can start with specific edited first frame, so that the code will skip the first-frame editing process. And we recommend you to do this since it performs much better. Particularly, I've execute Paint-by-Example on my ends with your inputs, where you can start with the following first edited frame:
 image.png (view on web)
 
If you meet any further problems, please do not hesitate to contact us again! Thanks!

**Comment by AlonzoLeeeooo** [comment]
> Thanks for your reply. However, I used InstructPix2Pix instead of Paint-by-Example. CUDA_VISIBLE_DEVICES=1 python inference.py --raft-checkpoint-path checkpoints/raft-things.pth --midas-checkpoint-path checkpoints/dpt_swin2_large_384.pt&nbsp;--u2net-checkpoint-path checkpoints/u2net.pth --stable-diffusion-checkpoint-path checkpoints/stable-diffusion-v1.5 --controlnet-checkpoint-path checkpoints/controlnet-depth --i2vgenxl-checkpoint-path checkpoints/i2vgenxl --ctrl-adapter-checkpoint-path checkpoints/ctrl-adapter-i2vgenxl-depth --completion-net-checkpoint-path checkpoints/50000.ckpt --image-editor-type instructpix2pix --image-editor-checkpoint-path checkpoints/instruct-pix2pix --source-video-frames inputs/frames/bear --external-guidance inputs/reference-images/raccoon.jpg --prompt "a raccoon" --outdir results

Okay great!

**Comment by Weiwenliang123** [comment]
Thank you for your reply. The effect is better than before.
![turn_the_bear_into_a_raccoon](https://github.com/user-attachments/assets/52724b6f-24f8-4455-b8b6-032f529a59f9)

**Comment by AlonzoLeeeooo** [comment]
Great! It seems that the issue is now solved, so I'll closed the issue. If you meet any further problems during your reproduction, feel free to leave a message under this issue again.
