### ISSUE TITLE
conda create env error

### ISSUE THREAD

**Issue by linghu-cell** [AlonzoLeeeooo/StableV2V#8]
When I use the following command: pip install - r requirements. txt, the following error occurs:
Processing /croot/brotli-split_1714483155106/work (from -r requirements.txt (line 17))
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/croot/brotli-split_1714483155106/work'

**Comment by AlonzoLeeeooo** [comment]
Hi @linghu-cell ,

Thank you for your information. We found that directly exporting configuration files with `pip` or `conda` might cause error, thus we recommend you to install the dependencies using our one-click scripts (updated in [this commit](https://github.com/AlonzoLeeeooo/StableV2V/commit/770b54f56e003485d72095946b644cd28ed457d2)), which should be able to work now since we have tested it on our ends.

Specifically, simply running `bash install_pip.sh` or `bash install_conda.sh` will install the dependencies with `pip` or `conda`, respectively.

Feel free to let us know if the error proceeds.

Best regards,
Chang

**Comment by AlonzoLeeeooo** [comment]
Hi @linghu-cell ,

This issue will closed for short, since the dependency problem is now solved. If you have any further questions about dependency installation, feel free to re-open this issue and contact us again.

Best regards,
Chang
